services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./attachments:/finance/app/static/attachments
    depends_on:
      - db

  db:
    image: mariadb:11.2.2
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:8080